---
title: ""
output: html_document
date: "2023-12-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggrepel)
tuesdata <- tidytuesdayR::tt_load(2023, week = 49)

life_expectancy <- janitor::clean_names(tuesdata$life_expectancy)
```

```{r}
life_expectancy %>% 
  filter(!is.na(code)) %>% 
  count(entity, wt = mean(life_expectancy), sort = T) %>% 
  rowid_to_column() %>% 
  ggplot(aes(rowid, n)) +
  geom_point() +
  geom_text_repel(aes(label = entity))
```

```{r}
life_expectancy %>% 
  filter(entity %in% c("Monaco", "Andorra", "Israel")) %>% 
  ggplot(aes(year, life_expectancy, col = entity)) +
  geom_line()
```

```{r}
world_data <- life_expectancy %>% 
  filter(entity %in% c("World"))

world_data %>% 
 ggplot(aes(year, life_expectancy, col = entity)) +
  geom_line()

model <- lm(life_expectancy ~ year, data = world_data)
broom::tidy(model)
```

```{r}
life_exp_model <-
  life_expectancy %>%
  filter(!is.na(code)) %>%
  nest(data = c(year, life_expectancy)) %>%
  mutate(model = map(data, ~ lm(life_expectancy ~ year, data = .x))) %>% 
  mutate(res_tidy = map(model, broom::tidy)) %>% 
  select(entity, res_tidy) %>% 
  unnest(cols = "res_tidy") %>% 
  filter(term == "year") %>% 
  mutate(p_adj = p.adjust(p.value))
```

```{r}
library(countrycode)

life_exp_model %>%
  mutate(continent = countrycode(
    sourcevar = entity,
    origin = "country.name",
    destination = "continent"
  )) %>% 
  ggplot(aes(estimate, p_adj, col = continent, label = entity)) +
  geom_point(alpha = 0.6) +
  scale_y_log10() +
  geom_text_repel() +
  labs(y = "P value", x = "Life expectancy (in years)",
       title = "Average increase in Life expectancy by country") +
  theme_minimal()
```

```{r}
life_expectancy %>% 
  filter(entity %in% c("Oman", "Zimbabwe", "Sweden")) %>% 
  ggplot(aes(year, life_expectancy, col = entity)) +
  geom_line()
```

